version: '2.1'
orbs:
  swissknife: roopakv/swissknife@0.69
jobs:
  obtain-value:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - run:
          command: echo "export APP_NAME=foobar" >> $BASH_ENV

  trigger-workflow:
    parameters:
      app_name:
        type: env_var_name
        default: APP_NAME
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: export CUSTOM_BRANCH="pipeline-params-cd"
      - swissknife/trigger-pipeline:
          custom-parameters: '{"app_name": <<parameters.app_name>>}'
          branch: CUSTOM_BRANCH
          #repo: (using default)
          #user: (using default)

workflows:
  main:
    jobs:
      - obtain-value
      - trigger-workflow:
          requires:
            - obtain-value