version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.10
    steps:
      - run: 
          command: |
            echo "Running the build job"
  test:
    docker:
      - image: cimg/base:2021.10
    steps:
      - run: 
          command: |
            echo "Running the test job"
  deploy:
    docker:
      - image: cimg/base:2021.10
    steps:
      - run: 
          command: |
            echo "Running the deploy job for ver << pipeline.git.tag >>!"
workflows:
  main:
    jobs:
      - build:
          name: Building application
      - test:
          name: Testing application
          requires:
            - Building application
      - hold-for-approval:
          name: Approval required to deploy application ver << pipeline.git.tag >>
          type: approval
          requires:
            - Testing application
          filters:
            branches:
              only: /release\/.*/
      - deploy:
          name: Deploying application ver << pipeline.git.tag >>
          requires:
            - Approval required to deploy application ver << pipeline.git.tag >>
          filters:
            branches:
              only: /release\/.*/

  redeploy:
    when:
      value: << pipeline.git.branch >>
      pattern: "^release/.+$"
    jobs:
      - approve-to-redeploy:
          name: Approve this job to redeploy ver << pipeline.git.tag >>
          type: approval
      - deploy:
          name: Redeploying application ver << pipeline.git.tag >>
          requires:
            - Approve this job to redeploy ver << pipeline.git.tag >>
            