version: 2.1

commands:
  notify_gerrit:
    steps:
      - run: 
          command: |
            echo "Success! Send "success" message to Gerrit."
            echo "API call goes here."
          when: on_success
      - run: 
          command: |
            echo "Failure. Send "failure" message to Gerrit."
            echo "API call goes here."
          when: on_fail

jobs:
  success:
    docker:
      - image: cimg/base:2021.10
    steps:
      - run: 
          command: echo "Performing some task..."
      - notify_gerrit
  failure:
    docker:
      - image: cimg/base:2021.10
    steps:
      - run: 
          command: echo "Performing some task..." && false
      - notify_gerrit


workflows:
  testing:
    jobs:
      - success
      - failure