version: 2.1


jobs:  
  run_a_script:
    docker:
      - image: cimg/base:2022.07
    steps:
      - run: 
          command: |
            echo "Generating script..."
            cat \<< EOF >> my_script.sh
            echo "This is the output of a script"
            EOF
      - run: 
          command: |
            echo "Executing script..."
            ./my_script.sh
workflows:
  main:
    jobs:
      - run_a_script