version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@3.0.0

jobs:
  oidc-test:
    docker:
      - image: cimg/base:2021.01
    steps:
      - aws-cli/setup
      - run:
          command: | 
            echo $CIRCLE_OIDC_TOKEN > ./token.txt
            aws sts get-caller-identity

workflows:
  main:
    jobs:
      - oidc-test:
          context: node-demo
          #context: empty-context