  version: 2.1

  jobs:
    my-successful-scan:
      docker:
        - image: cimg/base:2023.02
      steps:
        - run:
            command: |
              echo "Simulate getting successful scan results..."
              export RESULTS="SUCCESS"
              [[ $RESULTS == "SUCCESS" ]]

    my-failed-scan:
      docker:
        - image: cimg/base:2023.02
      steps:
        - run:
            command: |
              echo "Simulate getting failed scan results..."
              export RESULTS="FAIL"
              [[ $RESULTS == "SUCCESS" ]]

  workflows:
    use-my-orb:
      jobs:
        - my-successful-scan
        - my-failed-scan