version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@3.0.0

jobs:
  oidc-test:
    docker:
      - image: cimg/base:2021.01
    steps:
      - aws-cli/install
      - run:
          command: | 
            export AWS_OIDC_ROLE_ARN="arn:aws:iam::660990364978:role/jennings-oidc-demo"
            export AWS_REGION="ap-northeast-2"

            aws sts assume-role-with-web-identity \
            --role-arn ${AWS_OIDC_ROLE_ARN} \
            --role-session-name ${CIRCLE_USERNAME}-${CIRCLE_SHA1:0:5} \
            --web-identity-token ${CIRCLE_OIDC_TOKEN} > /tmp/aws-creds.txt

            export AWS_ACCESS_KEY_ID="$(cat /tmp/aws-creds.txt | jq -r ".Credentials.AccessKeyId")"
            export AWS_SECRET_ACCESS_KEY="$(cat /tmp/aws-creds.txt | jq -r ".Credentials.SecretAccessKey")"
            export AWS_SESSION_TOKEN="$(cat /tmp/aws-creds.txt | jqzs -r ".Credentials.SessionToken")"
            
            aws sts get-caller-identity

workflows:
  main:
    jobs:
      - oidc-test:
          #context: node-demo
          context: empty-context