version: 2.1

parameters:
  app_name: 
    type: string 
    default: test
  release:
    type: string
    default: "1.0"

commands:
  deploy:
    #parameters:
    steps:
      - run:
          command: |
            cat \<< EOF
            Deploying with the following params:
            
            App name: << pipeline.parameters.app_name >>
            Release: << pipeline.parameters.release >>
            Build number: << pipeline.number >>
            Branch: << pipeline.git.branch >>
            Environment: << pipeline.git.branch >>
            EOF

orbs: 
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  setup-aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
          role-arn: "arn:aws:iam::660990364978:role/jennings-oidc-demo"
          role-session-name: example-session
      - run: aws sts get-caller-identity #example AWS command
      
  run-deployment:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run: node --version #demonstrate node is installed
      - deploy
    



workflows:
  main:
    jobs:
      - setup-aws-cli:
          context: empty-context
      - run-deployment