version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.2

jobs:
  build-image-and-push-to-ecr:
    docker:
      - image: cimg/base:2022.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}-remote-docker-test"
          tag: "${CIRCLE_SHA1}"
          create-repo: true

workflows:
  version: 2
  main:   
    jobs:
    - build-image-and-push-to-ecr:
        context: aws-dev
        filters:
          branches:
            only:
              - /devel\/.*/
    - build-image-and-push-to-ecr:
        context: aws-prod
        filters:
          branches:
            only:
              - /prod\/.*/