# Borrowed from here: https://circleci.com/docs/2.0/runner-overview/?section=executors-and-images#referencing-your-runner-on-a-job
version: 2.1

jobs:
  runner:
    docker:
      - image: cimg/base:2021.03
    resource_class: jtreutel/runner-test-k8s
    steps:
      - run: echo "Hi, I'm on a Runner!"

workflows:
  version: 2
  testing:
    jobs:
      - runner