version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.10
    steps:
      - run: 
          command: |
            echo "Running the build job for ver << pipeline.git.tag >>!"
  test:
    docker:
      - image: cimg/base:2021.10
    steps:
      - run: 
          command: |
            echo "Running the test job for ver << pipeline.git.tag >>!"
  deploy:
    docker:
      - image: cimg/base:2021.10
    steps:
      - run: 
          command: |
            echo "Running the deploy job for ver << pipeline.git.tag >>!"
workflows:
  main:
    jobs:
      - build:
          name: Building application ver << pipeline.git.tag >>
      - test:
          name: Testing application ver << pipeline.git.tag >>
          requires:
            - Building application ver << pipeline.git.tag >>
      - hold-for-approval:
          name: Approval required to deploy application ver << pipeline.git.tag >>
          type: approval
          requires:
            - Testing application ver << pipeline.git.tag >>
      - deploy:
          name: Deploying application ver << pipeline.git.tag >>
          requires:
            - Approval required to deploy application ver << pipeline.git.tag >>

  redeploy:
    jobs:
      - approve-to-redeploy:
          name: Approve this job to redeploy ver << pipeline.git.tag >>
          type: approval
      - deploy:
          name: Redeploying application ver << pipeline.git.tag >>
          requires:
            - Approve this job to redeploy ver << pipeline.git.tag >>