version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:  
  env_var_to_file:
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2022.01.1
    steps:
      - run: 
          name: Write base64-encoded environment variable to file, then output file
          command: |
            echo $KEYSTORE | base64 -d > ./local.properties
            cat ./local.properties
      - run: 
          command: |
            cat /etc/issue || true
            lsb_release -a || true
workflows:
  main:
    jobs:
      - env_var_to_file:
          context: 
            - my-new-context