orbs: 
  jinja: jtreutel/jinja@9.9.9 #this version only exists on my Server instance

version: 2.1

jobs:
  render-file:
    executor: jinja/default
    environment:
      - FOOBAR: baz
    steps:
      - checkout
      - jinja/render:
          outputdir: jinja-orb-test/rendered/
          path: jinja-orb-test/example.txt.j2
      - run: cat jinja-orb-test/rendered/example.txt

workflows:
  testing:
    jobs:
      - render-file