version: 2.1

setup: true       # this allows you to use CircleCI's dynamic configuration feature

parameters:
  app_name:           # Determines which microservice will be deployed
    type: string 
    default: test
  release:            # Determines which version of the microservice will be deployed
    type: string
    default: "1.0.0"
  environment:        # Determines the environment in which to deploy
    type: string
    default: dev
  no_promotion:       # Determines whether or not to promote to the next environment
    type: string
    default: false


orbs:
  continuation: circleci/continuation@0.3.1   # the continuation orb is required in order to use dynamic configuration
  jinja: jtreutel/jinja@1.1.0


jobs:
  render-config-and-continue:  # this job is used to generate and pass the config file that will be used in the actual pipeline
    environment:
      APP_NAME: << pipeline.parameters.app_name >>
      RELEASE: << pipeline.parameters.release >>
      ENVIRONMENT: << pipeline.parameters.environment >>
      NO_PROMOTIION: << pipeline.parameters.no_promotion >>
    executor: jinja/default
    steps:
      - checkout
      - jinja/render:
          outputdir: ./.circleci
          path: ./.circleci/pipeline_config.yml.j2
      - continuation/continue:
          configuration_path: ./.circleci/pipeline_config.yml # use newly generated config to continue

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    jobs:
      - render-config-and-continue