version: 2.1
workflows:
  testing:
    jobs:
      - runner
      - long-runner
jobs:
  runner:
    machine: true
    resource_class: jtreutel/runner-test
    steps:
      - run: 
          command: echo "Hi I'm on Runners!" && sleep 120
          no_output_timeout: 60m
    parallelism: 8
  long-runner:
    machine: true
    resource_class: jtreutel/runner-test
    steps:
      - run: 
          command: echo "Hi I'm on Runners!" && sleep 1800
          no_output_timeout: 60m
    parallelism: 8