version: 2.1

jobs:  
  testing_job:
    docker:
      - image: cimg/base
    steps:
      - run: 
          name: Get list of all files
          command: ls -al
      - persist_to_workspace:
          root: .
          paths: 
              - .
  testing_job_2:
    docker:
      - image: cimg/base
    steps:
      - run:
          name: Create directory "foobar"
          command: mkdir testing
      - attach_workspace:
          at: foobar/
      - run:
          name: List files in directory "foobar"
          command: ls -al foobar


workflows:
  main:
    jobs:
      - testing_job
      - testing_job_2:
          requires:
              - testing_job