version: 2.1

jobs:
  validate:
    docker:
      - image: cimg/base:2021.01
    steps:
      - checkout
      - run:
          command: |
            curl https://api.github.com/repos/CircleCI-Public/circleci-cli/releases/latest | jq -r '.assets[] | select(.name | contains("linux_amd64")) | .browser_download_url' | wget -qi -
            find $(pwd) -type f -name 'circleci-cli_*' -printf "%f\n" | xargs tar xzvf
            find $(pwd) -type f -name 'circleci' | xargs -I % sudo mv % /usr/local/bin/ccicli
      - run:  for FILE in `find $(pwd) -type f -name '*config.yml'`; do echo; echo "Validating $FILE"; ccicli config validate $FILE; done

workflows:
  main:
    jobs:
      - validate