# Borrowed from here: https://circleci.com/docs/2.0/runner-overview/?section=executors-and-images#referencing-your-runner-on-a-job
version: 2.1

jobs:
  runner:
    machine: true
    resource_class: jtreutel/runner-test-k8s
    steps:
      - run: echo "Hi, I'm on a Runner!"
  runner-docker-in-docker:
    machine: true
    resource_class: jtreutel/runner-test-k8s
    steps:
      - run: |
          fdisk -l
workflows:
  version: 2
  testing:
    jobs:
      - runner
      - runner-docker-in-docker