version: 2.1

test: &test
    docker:
      - image: cimg/base:2021.01
    steps:
      - run:  echo "Running tests for ${ENV_NAME} environment..." >> ./running_tests && cat ./running_tests.txt  #doing this because context vars are masked in output



jobs:
  build:
    docker:
      - image: cimg/base:2021.01
    steps:
      - run:  echo Building the application...
  test-demo:
    <<: *test
  test-dev:
    <<: *test
  test-staging:
    <<: *test
  test-prod:
    <<: *test

workflows:
  version: 2
  main:
    jobs:
      - build
      - test-demo:
          context: test-demo-vars
          requires:
            - build
          filters:
            branches:
              only: /demo\/.*/
      - test-dev:
          context: test-dev-vars
          requires:
            - build
          filters:
            branches:
              only: /dev\/.*/
      - test-staging:
          context: test-staging-vars
          requires:
            - build
          filters:
            branches:
              only: /staging\/.*/
      - test-prod:
          context: test-prod-vars
          requires:
            - build
          filters:
            branches:
              only: master



