version: 2.1 
jobs:
  build:
    docker:
      - image: cimg/base:2022.04
    steps:
      - run:
          name: Do the build
          command: echo "Build steps go here."
      - run:
          name: Fail the build
          command: echo "Simulate build failure." && false
      - run:
          name: Store results
          command: echo "Store the results somewhere."
          when: always
      - run:
          name: Approve the manual approval job
          command: |
            APPROVAL_JOB_ID=$(curl --request GET --url "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/job" --header "Circle-Token: ${CIRCLE_TOKEN}" | jq -r '.items[] | select(.type == "approval") | .id')
            curl --request POST https://circleci.com/api/v2/workflow/${CIRCLECI_WORKFLOW_ID}/approve/${APPROVAL_JOB_ID} --header "Circle-Token: ${CIRCLE_TOKEN}"
          when: always
  upload_results:
    machine: true
    resource_class: jtreutel/runner-test
    steps:
      - run:
          name: Do the build
          command: echo "Build steps go here."




workflows:
  main:
    jobs:
      - build
      - manual-approval:
          type: approval
          requires:
            - build
      - upload_results:
          requires:
            - manual-approval