version: 2.1

commands:
  validate-approval:
    description: "Validate whether deployment was properly approved."
    steps:
      - run: |
          WORKFLOW_JOBS=$(curl -H "Circle-Token: $CIRCLECI_API_KEY" "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/job")
          CURRENT_JOB_DEPENDENCIES=$(echo "$WORKFLOW_JOBS" | jq -cr ".items[] | select(.id == \"$CIRCLE_WORKFLOW_JOB_ID\") | .dependencies[]")
          APPROVAL_JOBS=$(echo "$WORKFLOW_JOBS" | jq -cr '.items[] | select(.type == "approval")')

          for JOB in $APPROVAL_JOBS
          do
            JOB_ID=$(echo "$JOB" | jq -r .id)
            for DEPENDENCY_ID in $CURRENT_JOB_DEPENDENCIES
            do
              if [ "$DEPENDENCY_ID" = "$JOB_ID" ]; then
                APPROVED_BY=$(echo "$JOB" | jq -r .approved_by)
              fi
            done
          done

          if [ "$APPROVED_BY" = "" ]; then
            echo "Could not find linked approval job. Make sure you run this step in a job that depends on an approval job."
            exit 1
          fi

          APPROVER=$(curl -H "Circle-Token: $CIRCLECI_API_KEY" "https://circleci.com/api/v2/user/${APPROVED_BY}")
          APPROVER_NAME=$(echo "$APPROVER" | jq -r '"\(.name) (\(.login))"')
          echo "Approver: $APPROVER_NAME"

jobs:
  build-and-test:
    docker:
      - image: cimg/base:2023.07
    steps:
      - run:
          name: Run build and tests
          command: echo "Running build and tests!"
  verify:
    docker:
      - image: cimg/base:2023.07
    steps:
      - validate-approval
  deploy:
    docker:
      - image: cimg/base:2023.07
    steps:
      - run:
          name: Run tests
          command: echo "Running deployment!"


workflows:
  use-my-orb:
    jobs:
      - build-and-test
      - wait-for-approval:
          type: approval
          requires:
            - build-and-test
      - verify:
          requires:
            - wait-for-approval
      - deploy:
          requires:
            - verify