version: 2.1

jobs:
  secrets:
    docker:
      - image: cimg/base:2021.01
    steps:
      - run:  echo ${SLACK_ACCESS_TOKEN} >> ./slack.txt
      - run:  echo ${SLACK_DEFAULT_CHANNEL} >> ./slack.txt

workflows:
  build-flow:
    jobs:
      - secrets:
          context: Demos-context



