  version: 2.1
  orbs:
    vault: smaeda-ks/orb-hashicorp-vault-cli@0.1.6

  jobs:
    my-job:
      docker:
        - image: cimg/base:2023.02
      steps:
        - checkout
        - run:
            name: fdd
            command: |
              echo $VAULT_CACERT_B64 > vault_ca.crt
              export VAULT_CACERT="./vault_ca.crt"
        # Install Vault
        - vault/install
        # Authenticate using OIDC and obtain token
        # This will automatically set VAULT_TOKEN env variable
        - vault/auth-oidc:
            vault-address: "https://34.85.17.240:8200"
            vault-role: "circleci-demo"
        - run:
            name: Get secret
            command: |
              # export secret using $BASH_ENV
              # so it can be referenced by subsequent steps within the job
              FOO=$(vault kv get -field=password secret/data/circleci-demo/demo-secrets)
              echo $FOO
              echo "export SECRET_FOO=${FOO}" >> $BASH_ENV
        # Revoke Vault token after finishing all steps
        - vault/revoke-self
  workflows:
    use-my-orb:
      jobs:
        - my-job:
            # You must use context for jobs require OIDC
            context: empty-context