version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "This is the build job!"
      - run:  echo ${SLACK_ACCESS_TOKEN} >> ./slack.txt
      - run:  echo ${SLACK_DEFAULT_CHANNEL} >> ./slack.txt
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "This is the test job!"
  deploy-to-qa-env:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Deploying to QA environment for testing because branch starts with qa."

workflows:
  example:
    jobs:
      - build
      - test:
          context: Demos-context
          requires:
            - build
      - deploy-to-qa-env:
          requires:
            - test
          filters:
            #branches:             #matches branches starting with "qa"; see here for more info: https://circleci.com/docs/2.0/workflows/#using-regular-expressions-to-filter-tags-and-branches
            #    only: /qa.*/        
            tags:                #you could also use tags instead
              only: /qa.*/ 