version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.01
    steps:
      - run:  echo foobar
  test:
    docker:
      - image: cimg/base:2021.01
    steps:
      - run:  echo foobar
  deploy:
    docker:
      - image: cimg/base:2021.01
    steps:
      - run:  echo foobar

workflows:
  version: 2
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold_for_deploy:
          type: approval
          requires:
            - build
      - deploy:
          requires:
           - hold_for_deploy



